/**
 * MpesaExpressAPIService
 * Mpesa Express Checkout API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import STKPushResponseHeader from './STKPushResponseHeader';

/**
 * The STKPushResponse model module.
 * @module org.wso2.client.model.MpesaExpressAPIService/STKPushResponse
 * @version 1.0.0
 */
class STKPushResponse {
    /**
     * Constructs a new <code>STKPushResponse</code>.
     * @alias module:org.wso2.client.model.MpesaExpressAPIService/STKPushResponse
     * @param header {module:org.wso2.client.model.MpesaExpressAPIService/STKPushResponseHeader} 
     * @param response {Object} 
     */
    constructor(header, response) { 
        
        STKPushResponse.initialize(this, header, response);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, header, response) { 
        obj['header'] = header;
        obj['response'] = response;
    }

    /**
     * Constructs a <code>STKPushResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:org.wso2.client.model.MpesaExpressAPIService/STKPushResponse} obj Optional instance to populate.
     * @return {module:org.wso2.client.model.MpesaExpressAPIService/STKPushResponse} The populated <code>STKPushResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new STKPushResponse();

            if (data.hasOwnProperty('header')) {
                obj['header'] = STKPushResponseHeader.constructFromObject(data['header']);
            }
            if (data.hasOwnProperty('response')) {
                obj['response'] = ApiClient.convertToType(data['response'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {module:org.wso2.client.model.MpesaExpressAPIService/STKPushResponseHeader} header
 */
STKPushResponse.prototype['header'] = undefined;

/**
 * @member {Object} response
 */
STKPushResponse.prototype['response'] = undefined;






export default STKPushResponse;

