/**
 * MpesaExpressAPIService
 * Mpesa Express Checkout API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MpesaExpressApiService);
  }
}(this, function(expect, MpesaExpressApiService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MpesaExpressApiService.STKPushRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('STKPushRequest', function() {
    it('should create an instance of STKPushRequest', function() {
      // uncomment below and update the code to test STKPushRequest
      //var instane = new MpesaExpressApiService.STKPushRequest();
      //expect(instance).to.be.a(MpesaExpressApiService.STKPushRequest);
    });

    it('should have the property phoneNumber (base name: "phoneNumber")', function() {
      // uncomment below and update the code to test the property phoneNumber
      //var instane = new MpesaExpressApiService.STKPushRequest();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instane = new MpesaExpressApiService.STKPushRequest();
      //expect(instance).to.be();
    });

    it('should have the property invoiceNumber (base name: "invoiceNumber")', function() {
      // uncomment below and update the code to test the property invoiceNumber
      //var instane = new MpesaExpressApiService.STKPushRequest();
      //expect(instance).to.be();
    });

    it('should have the property sharedShortCode (base name: "sharedShortCode")', function() {
      // uncomment below and update the code to test the property sharedShortCode
      //var instane = new MpesaExpressApiService.STKPushRequest();
      //expect(instance).to.be();
    });

    it('should have the property orgShortCode (base name: "orgShortCode")', function() {
      // uncomment below and update the code to test the property orgShortCode
      //var instane = new MpesaExpressApiService.STKPushRequest();
      //expect(instance).to.be();
    });

    it('should have the property orgPassKey (base name: "orgPassKey")', function() {
      // uncomment below and update the code to test the property orgPassKey
      //var instane = new MpesaExpressApiService.STKPushRequest();
      //expect(instance).to.be();
    });

    it('should have the property callbackUrl (base name: "callbackUrl")', function() {
      // uncomment below and update the code to test the property callbackUrl
      //var instane = new MpesaExpressApiService.STKPushRequest();
      //expect(instance).to.be();
    });

    it('should have the property transactionDescription (base name: "transactionDescription")', function() {
      // uncomment below and update the code to test the property transactionDescription
      //var instane = new MpesaExpressApiService.STKPushRequest();
      //expect(instance).to.be();
    });

  });

}));
